name: Postman Collection Workflow


on:
  push: 
    branches: [main]
  workflow_dispatch:
  schedule:
     - cron: 30 02 * * *
     - cron: 30 02 * * 0
jobs:
  run-postman-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2
        
      - name: Setup Node.js and NPM
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '22'
          
      - name: Install Newman and Html-extra globally
        run:  |
              npm install -g newman 
              npm install -g newman-reporter-htmlextra
      - name: Run Postman collection with Newman
        run:  newman run 'In-WarrantyFlow Collection_Ext_CSV.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testData.csv \
              -r cli,htmlextra
      
       
          

        
        
        
      
